apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
  SPRING_JPA_HIBERNATE_DDL_AUTO: none
  SPRING_LIQUIBASE_ENABLED: "true"
